# note(@botoaca): This script plots the coordinates of the pictures made from the ISS during GreenTea's experiment run.
#                 It should be known that pictures were only taken during daytime, as land was only visible then.
#                 The script uses the data from the report file, which is generated by experiment's script.

import requests
import ciso8601
import geopandas as gpd
import matplotlib.pyplot as plt

__REPORT_TXT_FILE_PATH = "GreenTea/GreenTea/GREENTEA_DATA/GREENTEA_DATA_REPORT.txt"
__WHEREISTHEISS_API_URL = "https://api.wheretheiss.at/v1/satellites/25544/"

def get_pos_to_file():
    data = [[]]
    with open(__REPORT_TXT_FILE_PATH, "r") as f:
        data = [l.rstrip("\n").split(" - ") for l in f]
    times = [data[i][2] for i in range(len(data))]
    times = [ciso8601.parse_datetime(t).timestamp() for t in times]
    iss_positions = []
    for i in range(0, len(data), 10):
        req_times = times[i:i+10]
        req_times = [str(t) for t in req_times]
        req_times = ",".join(req_times)
        req = requests.get(__WHEREISTHEISS_API_URL + "positions?timestamps=" + req_times)
        req = req.json()
        iss_positions.append([[req[j]["latitude"], req[j]["longitude"]] for j in range(len(req))])
    
    with open("iss_positions.txt", "w") as f:
        for i in range(len(iss_positions)):
            for j in range(len(iss_positions[i])):
                f.write(str(iss_positions[i][j][0]) + "," + str(iss_positions[i][j][1]) + "\n")

def main():
    pos = []
    while True:
        try:
            with open("iss_positions.txt", "r") as f:
                pos = [l.rstrip("\n").split(",") for l in f]
                pos = [[float(pos[i][0]), float(pos[i][1])] for i in range(len(pos))]
            break
        except FileNotFoundError:
            get_pos_to_file()
        
    world = gpd.read_file(gpd.datasets.get_path("naturalearth_lowres"))
    _, ax = plt.subplots(figsize=(12, 6))
    world.plot(ax=ax, color="lightgray", edgecolor="black")
    ax.scatter(
        [pos[i][1] for i in range(len(pos))], [pos[i][0] for i in range(len(pos))],
        s=10,
        marker=".",
        color="red",
        alpha=1
    )

    ax.set_xlim(-180, 180)
    ax.set_ylim(-90, 90)
    ax.set_xlabel("Latitude")
    ax.set_ylabel("Longitude")
    ax.set_title("Coordinates of the pictures made from the ISS during GreenTea\'s experiment run")

    plt.savefig("iss_positions_plot.png", dpi=300)

if __name__ == "__main__":
    main()
